simple null checks
rubicon-oss/NullableReferenceTypesRewriter pull request #2
Opened 2020-03-16 10:03 UTC by dkudernatsch

Checks if there is a CanBeNullAttribute
Checks if it directly returns null keyword
Checks if it directly returns method that can return null

2020-03-16 11:15 UTC, iam-mholle requested changes
Please add tests.

2020-03-16 11:15 UTC, iam-mholle commented on ConsoleApplication/MethodNullAnnotator.cs
> +﻿using System;
Missing license header

2020-03-16 11:15 UTC, iam-mholle commented on ConsoleApplication/MethodNullAnnotator.cs
> + public class MethodNullAnnotator : CSharpSyntaxRewriter
Wrong indentation

2020-03-16 11:15 UTC, iam-mholle commented on ConsoleApplication/MethodNullAnnotator.cs
> +        return node;
```suggestion
      var returnsNull = HasCanBeNullAttribute (node)
                        || ReturnsNull (node, _semanticModel);

      if (!returnsNull)
        return node;
```

2020-03-16 11:15 UTC, iam-mholle commented on ConsoleApplication/MethodNullAnnotator.cs
> +namespace NullableTypeSetter.ConsoleApplication
`NullableTypeSetter.X` should be `NullableReferenceTypesRewriter.X`

2020-03-16 11:15 UTC, iam-mholle commented on ConsoleApplication/MethodNullAnnotator.cs
> +          .Any (attr => attr.Name.ToString().EndsWith ("CanBeNull"));
Does roslyn expose `CanBeNullAttribute` as `CanBeNull`? Automated tests would really help.

2020-03-16 11:15 UTC, iam-mholle commented on ConsoleApplication/MethodNullAnnotator.cs
> +        Console.WriteLine (expression);
Why are we writing to console here?

2020-03-16 11:15 UTC, iam-mholle commented on ConsoleApplication/MethodNullAnnotator.cs
> + public class MethodNullAnnotator : CSharpSyntaxRewriter
~Consider ordering the methods by accessibility.~
Multiple methods can be made private

2020-03-16 11:15 UTC, iam-mholle commented on ConsoleApplication/Program.cs
> +using System.IO;
Missing license header

2020-03-16 11:15 UTC, iam-mholle commented on ConsoleApplication/Program.cs
> +      return workspace.OpenSolutionAsync (@"C:\Development\Remotion-git\Remotion.sln");
This does not seem right 😉 
```suggestion
      return workspace.OpenSolutionAsync (solutionPath);
```

2020-03-16 11:15 UTC, iam-mholle commented on ConsoleApplication/Program.cs
> +    public static Task<Solution> LoadSolutionSpace (string solutionPath)
Why is this `public`?

2020-03-20 12:11 UTC, iam-mholle commented
@dkudernatsch Is this one obsolete with https://github.com/rubicon-oss/NullableReferenceTypesRewriter/pull/4?

2020-03-20 12:15 UTC, dkudernatsch commented
> 
> 
> @dkudernatsch Is this one obsolete with #4?

yes this was a draft pr anyway and i added lots of new stuff.
The requested changes should be all done however

2020-03-31 12:26 UTC, closed without merging

2020-03-31 12:26 UTC, iam-mholle commented
Closed in favor of #4.